// <auto-generated />
namespace TourCore.Infrastructure.SqlServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddTransports : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTransports));
        
        string IMigrationMetadata.Id
        {
            get { return "202605051345536_AddTransports"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
