// <auto-generated />
namespace TourCore.Infrastructure.SqlServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddBusSchedules : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBusSchedules));
        
        string IMigrationMetadata.Id
        {
            get { return "202605041241059_AddBusSchedules"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
